language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  # - docker build -t udagram-api-feed ./udagram-api-feed
  # - docker build -t udagram-api-user ./udagram-api-user
  # - docker build -t udagram-frontend ./udagram-frontend
  # - docker build -t reverseproxy ./udagram-reverseproxy
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed fidazik/udagram-api-feed:v3
  - docker tag udagram-api-user fidazik/udagram-api-user:v3
  - docker tag udagram-frontend:local fidazik/udagram-frontend:v3
  - docker tag reverseproxy fidazik/reverseproxy:v3

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fidazik/udagram-api-feed:v3
  - docker push fidazik/udagram-api-user:v3
  - docker push fidazik/udagram-frontend:v3
  - docker push fidazik/reverseproxy:v3